---

include:
  - board: nice_nano//zmk
    shield: charybdis_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano//zmk
    shield: charybdis_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  - board: nice_nano//zmk
    shield: charybdis_dongle

  - board: nice_nano//zmk
    shield: settings_reset
